### ISSUE TITLE
support enable_shielded_nodes

### ISSUE THREAD

**Issue by marekaf** [gruntwork-io/terraform-google-gke#112]
Hi,
I'd like to be able to enable Shielded Nodes feature

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_shielded_nodes

and have its default set to `true` as it is a best practice in the sec-hardening guide. I'll submit a PR later on.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
