### ISSUE TITLE
Support setting Release Channels

### ISSUE THREAD

**Issue by MeNsaaH** [gruntwork-io/terraform-google-gke#116]
Release channels provide more control over automatic upgrades of GKE clusters. By default it's set to `UNSPECIFIED` which presents upgrade options when running terraform and a new GKE master version exists. For production clusters, `STABLE` is the recommended release channel.

**Comment by brianpham** [comment]
I agree with this by the way. We definitely want to set to STABLE or at least the option to specify it.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
