### ISSUE TITLE
IpAllocation Policy - Secondary Range Names

### ISSUE THREAD

**Issue by eliasscosta** [gruntwork-io/terraform-google-gke#118]
Hello everyone, 

This week I begin to receive this error: 
```Error: googleapi: Error 400: Pod secondary range name (public-services) should not be the same as service secondary range name., badRequest``` when I  recreate a cluster. 

I in my plan module add the same name in cluster and service secondary ranges names. 

``` 
+ ip_allocation_policy {
          + cluster_ipv4_cidr_block       = (known after apply)
          + cluster_secondary_range_name  = "public-services"
          + services_ipv4_cidr_block      = (known after apply)
          + services_secondary_range_name = "public-services"
        }
```

Look in detail the name is from vpc_network module and isn't possible to create a new subnetwork with a different name on this module. 

I believe Google made few changes to the API.

**Comment by Jojoooo1** [comment]
Same errors

**Comment by Taiwo-babson** [comment]
I am also having same error.

**Comment by Jojoooo1** [comment]
Add to create another block of ip for pod

**Comment by brianpham** [comment]
Seeing the same issue right now. What did you do exactly to fix the issue? @Jojoooo1

**Comment by brianpham** [comment]
Doing some testing right now, but I changed the name for services_secondary_range_name. This should fix the issue hopefully too. Need to verify the cluster is working properly after it comes up.

**Comment by Jojoooo1** [comment]
secondary_ip_range {
    range_name = "public-services"
    ip_cidr_range = cidrsubnet(
      var.secondary_cidr_block,
      var.secondary_cidr_subnetwork_width_delta,
      0
    )
  }

  secondary_ip_range {
    range_name = "public-cluster"
    ip_cidr_range = cidrsubnet(
      var.secondary_cidr_block,
      var.secondary_cidr_subnetwork_width_delta,
      1 * (1 + var.secondary_cidr_subnetwork_spacing)
    )
  }

**Comment by brianpham** [comment]
@Jojoooo1 Thanks. So you have to make changes to both the vpc-network module and the gke-cluster module?

**Comment by brianpham** [comment]
Nevermind. I was able to finally get it to work by doing what you suggested @Jojoooo1. 

Had to patch both modules for it to work properly.
https://github.com/brianpham/terraform-google-gke/commit/f2bd4ce91ba615a50cde366d84aaf27b77477b8e
https://github.com/brianpham/terraform-google-network/commit/10f743327dacb3e4552da288b03f965d3881a835

Another workaround is just commenting out this line if you don't really want to point to your cidr block. GKE will just manage it for you if you don't include it. 
https://github.com/gruntwork-io/terraform-google-gke/blob/master/modules/gke-cluster/main.tf#L71

**Comment by robmorgan** [comment]
Hi everyone, thank you for raising this issue. Did anybody need to migrate Terraform state after changing/adding the additional `secondary_ip_range`? I'm mindful of having to publish a migration guide in order to get a quick fix out or finding a way to maintain backwards compatibility. I have a feeling the latter will not be possible in this case as it seems we are conflicting with GCP's API.

**Comment by brianpham** [comment]
@robmorgan Not sure about that. I re-created my cluster since I had to update the cidr blocks.

**Comment by robmorgan** [comment]
Released in https://github.com/gruntwork-io/terraform-google-gke/releases/tag/v0.8.0
