### ISSUE TITLE
Is this Repo still maintained ?

### ISSUE THREAD

**Issue by SMR39** [gruntwork-io/terraform-google-gke#129]
I am having hard time that none of the pull requests for GKE add-ons are being reviewed and merged by the moderators. 

The review seems pretty straight forward its just adding a flag. Whats taking so long to approve these addon PRs 

I would like to see these addons added to this module. 

- Config Connector https://github.com/gruntwork-io/terraform-google-gke/pull/114
- Shielded GKE nodes https://github.com/gruntwork-io/terraform-google-gke/pull/113
- Filestore CSI driver (not there yet)
- node local DNS cache https://github.com/gruntwork-io/terraform-google-gke/pull/128

**Comment by brianpham** [comment]
I am curious about this as well. I could love to continue using this module, but it has been getting harder to do so because it's not getting updated frequently enough.

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. The short answer is not at the moment. Please see a more detailed explanation below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
