### ISSUE TITLE
Fix Google Provider 4.0.0 Breaking Changes

### ISSUE THREAD

**Issue by brianpham** [gruntwork-io/terraform-google-gke#133]
I am seeing the following error when upgrading google-provider to 4.0.0. Looks like there are some breaking changes in this release as noted in https://github.com/hashicorp/terraform-provider-google/releases 

```
│ Error: Insufficient client_certificate_config blocks
│ 
│   on .terraform/modules/gke_cluster/modules/gke-cluster/main.tf line 107, in resource "google_container_cluster" "cluster":
│  107:   master_auth {
│ 
│ At least 1 "client_certificate_config" blocks are required.
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/gke_cluster/modules/gke-cluster/main.tf line 108, in resource "google_container_cluster" "cluster":
│  108:     username = var.basic_auth_username
│ 
│ An argument named "username" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/gke_cluster/modules/gke-cluster/main.tf line 109, in resource "google_container_cluster" "cluster":
│  109:     password = var.basic_auth_password
│ 
│ An argument named "password" is not expected here.
```

**Comment by brianpham** [comment]
Attempt to fix with https://github.com/gruntwork-io/terraform-google-gke/pull/134

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
