### ISSUE TITLE
Docker container runtimes is not supported

### ISSUE THREAD

**Issue by Rahulsharma0810** [gruntwork-io/terraform-google-gke#140]
While using the code 

https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-private-cluster with latest module `source = "github.com/gruntwork-io/terraform-google-gke.git//modules/gke-cluster"`

Output Reports 

```
Plan: 1 to add, 0 to change, 0 to destroy.
google_container_node_pool.node_pool: Creating...
╷
│ Error: error creating NodePool: googleapi: Error 400: Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24., badRequest
│
│   with google_container_node_pool.node_pool,
│   on main.tf line 93, in resource "google_container_node_pool" "node_pool":
│   93: resource "google_container_node_pool" "node_pool" {
│
╵
❯

```

**Comment by Etiene** [comment]
Notice from the [README](https://github.com/gruntwork-io/terraform-google-gke): 

> Sunset notice
> 
> We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.
> 
> If you wish to be the maintainer for this project, we are open to considering that. Please contact us at [support@gruntwork.io](mailto:support@gruntwork.io).

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
