### ISSUE TITLE
Optional NAT Gateway for GKE 

### ISSUE THREAD

**Issue by 123BLiN** [gruntwork-io/terraform-google-gke#37]
Thanks a lot for your hard work!
Do you think NAT Gateway can be useful from the example here - https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/tree/master/examples/gke-ha-nat-gateway

**Comment by autero1** [comment]
Hi, the networking part has actually been implemented in a separate module: https://github.com/gruntwork-io/terraform-google-network. With that module you can control the networking aspects quite precisely. Take a look at the [access tier table](https://github.com/gruntwork-io/terraform-google-network/tree/master/modules/vpc-network#access-tier) for further details.

**Comment by robmorgan** [comment]
Hi @123BLiN, I'm going to close this issue for now. Let me know if you have any further questions.
