### ISSUE TITLE
Istio support

### ISSUE THREAD

**Issue by dkirrane** [gruntwork-io/terraform-google-gke#38]
Would be good to have an option to install Istio:

- enable Istio addon https://cloud.google.com/istio/docs/istio-on-gke/installing
-  or do manual steps to install Istio https://cloud.google.com/kubernetes-engine/docs/tutorials/installing-istio

**Comment by robmorgan** [comment]
hi @dkirrane, thanks for your issue. I agree - Istio support may be a good addition. Personally, I'm not very familiar with it and it's level of maturity but I'll leave this issue open for now. If there's enough interest it might be a worthy enhancement for this module.

**Comment by MikeyUchiha** [comment]
I would be interested in having an example of how to do a manual install of istio using Terraform. @robmorgan

**Comment by cpini** [comment]
hi @robmorgan awesome module but agree that addons_config support would be really helpful, this would enable support for Istio and other config values https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#addons_config.

many thanks

**Comment by robmorgan** [comment]
Hi @cpini thanks for your feedback. Personally, I don't have time at the moment to work on any additional features, but PRs would be very welcome!

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
