### ISSUE TITLE
GRUNTWORK_PHILOSOPHY.md table has GCP examples

### ISSUE THREAD

**Issue by rileykarson** [gruntwork-io/terraform-google-gke#4]
All of the examples in https://github.com/gruntwork-io/terraform-google-gke/blob/master/GRUNTWORK_PHILOSOPHY.md of cloud provider resources are AWS-based; once we have support for some GCP resources/modules, let's update the version of GRUNTWORK_PHILOSOPHY.md in this repo to include their GCP equivalents.

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
