### ISSUE TITLE
Feature: expose tiller_history_max from k8s-tiller module or set a default that is not 0

### ISSUE THREAD

**Issue by tverhoeven** [gruntwork-io/terraform-google-gke#47]
To prevent stability issues when having a long history of helm releases (and thus many secrets in the k8s store). Could either the setting of the historyMax be exposed in the gke-cluster module or that the default is set to not 0?

**Comment by robmorgan** [comment]
hi @tverhoeven, thanks for your issue. Yes, I don't think I have any problem with that. Do you want to have a go at submitting a PR? If not I'll revisit when I have more time.

**Comment by robmorgan** [comment]
Related issue: https://github.com/gruntwork-io/terraform-kubernetes-helm/issues/36

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
