### ISSUE TITLE
Error 403: Required 'compute.networks.create'

### ISSUE THREAD

**Issue by dkirrane** [gruntwork-io/terraform-google-gke#53]
I'm hitting the following on `terraform apply`
```
Error: Error creating Network: googleapi: Error 403: Required 'compute.networks.create' permission for 'projects/my-proj/global/networks/cluster-dev1-network-yl0n-network', forbidden

  on .terraform\modules\vpc_network\modules\vpc-network\main.tf line 12, in resource "google_compute_network" "vpc":
  12: resource "google_compute_network" "vpc" {
```

I've setup a Service Account key with `GOOGLE_APPLICATION_CREDENTIALS="C:\terraform-2baedc723d70.json"` roles:
![image](https://user-images.githubusercontent.com/1280116/62078502-ad81dc80-b244-11e9-998e-3f3b9d67cdba.png)

```
$ terraform version
Terraform v0.12.5
+ provider.external v1.2.0
+ provider.google v2.7.0
+ provider.google-beta v2.7.0
+ provider.helm v0.10.0
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.0.1
```

**Comment by robmorgan** [comment]
hi @dkirrane,

It looks like it may be related to: https://github.com/terraform-providers/terraform-provider-google/issues/2081

Could you ensure only the following roles are added and remove the others?

* Compute admin
* Compute network admin
* Kubernetes Engine cluster admin
* Service account admin

Does that make a difference?

**Comment by dkirrane** [comment]
That worked after I deletd the old keys for the service account and created key. 
Also, it looks it doesn't work if you rename the downloaded service account key (.json file)

**Comment by dkirrane** [comment]
Getting a new error noe
```
Error: Error retrieving IAM policy for project "my-project": googleapi: Error 403: The caller does not have permission, forbidden

  on ..\..\modules\gke-service-account\main.tf line 8, in resource "google_project_iam_member" "service_account-log_writer":
   8: resource "google_project_iam_member" "service_account-log_writer" {
```

I have the Service account role.

**Comment by robmorgan** [comment]
hi @dkirrane are you running Terraform in the root of the `terraform-google-gke` repository or using another one of the examples we provide?

**Comment by dkirrane** [comment]
Hi @robmorgan I'm using `terraform-google-gke/examples/gke-basic-tiller/`

**Comment by dkirrane** [comment]
Tried from the root directory too same error. I'm on the master branch

**Comment by dkirrane** [comment]
Turns out I needed both of these roles:
```
    Service Account Admin
    Service Account User
```

**Comment by rbizzell40** [comment]
I am running into the same error  and my SA account has Compute Network Admin
Compute Network Admin
Editor
Service Account Admin
Service Account User
* google_compute_network.network: Error creating Network: googleapi: Error 403: Required 'compute.networks.create' permission for 'projects/cloud-build-demo-251418/global/networks/dev', forbidden
* module.vpc.module.vpc.google_compute_network.network: 1 error occurred:
1 error occurred:

Error: Error applying plan:

**Comment by kyrogue** [comment]
ensure you are using the correct service account for the correct google project id, turns out i was using a service account for another project, thus it had no permission
