### ISSUE TITLE
Adding kuberneted context after deployment

### ISSUE THREAD

**Issue by arashbi** [gruntwork-io/terraform-google-gke#66]
Can I somehow add the newly created kubernetes context to the kubernetes provider; so that I can start deploying my applications to the cluster seamlessly?

**Comment by yorinasub17** [comment]
Hi the `gke-basic-tiller` example has an example of how to configure the kubernetes provider in the same terraform module as the one that is deploying the cluster. See: https://github.com/gruntwork-io/terraform-google-gke/blob/master/examples/gke-basic-tiller/main.tf#L57
