### ISSUE TITLE
Proposal: Change hardcoded module values to variables

### ISSUE THREAD

**Issue by AlbertasG** [gruntwork-io/terraform-google-gke#69]
I'm currently working on fork that would change statically typed values (node pool sizes, machine types, naming) in the module.

Is there any reason that at the moment we have those hard coded? Am I missing something?

Would this be a reasonable PR to implement?

Current main.tf: 
```
  autoscaling {
    min_node_count = "1"
    max_node_count = "5"
  }
```
Example of proposal main.tf: 
```
  autoscaling {
    min_node_count = var.autoscaling_min_node_count
    max_node_count = var.autoscaling_max_node_count
  }
```

**Comment by autero1** [comment]
Hi @AlbertasG  The root of the repo is not the module implementation, instead it's just an example - and as such, not supposed to used as a `terraform` module. 

The actual implementation is under [modules](https://github.com/gruntwork-io/terraform-google-gke/tree/master/modules). For clarification, see https://github.com/gruntwork-io/terraform-google-gke/#whats-in-this-repo and https://github.com/gruntwork-io/terraform-google-gke/tree/master/modules/gke-cluster#how-do-you-use-this-module.

**Comment by AlbertasG** [comment]
Thanks for clarifying. Closing.
