### ISSUE TITLE
Can someone assure that the dependencies keyword actually works 

### ISSUE THREAD

**Issue by buamod** [gruntwork-io/terraform-google-gke#70]
Accroding to terraform this feature is still not there yet 

  dependencies = [null_resource.tiller_tls_certs.id, kubernetes_cluster_role_binding.user.id]

Which is a dependency within a module 

https://github.com/hashicorp/terraform/issues/10462#issuecomment-561460993

**Comment by autero1** [comment]
Hi @buamod 

We use the `dependencies` input variable to work around the module dependency issue. You can see detailed explanation here: https://github.com/gruntwork-io/terraform-kubernetes-helm/blob/3ff147f9ce1e69427b1a2f0e81a5e99d380a1a19/modules/k8s-tiller/variables.tf#L193

**Comment by buamod** [comment]
Thanks @autero1

**Comment by autero1** [comment]
Closing this
