### ISSUE TITLE
google-beta 3 removed the kubernetes_dashboard

### ISSUE THREAD

**Issue by arashbi** [gruntwork-io/terraform-google-gke#71]
Running on 

> Terraform v0.12.16
>+ provider.google v2.9.1
>+ provider.google-beta v3.0.0-beta.1
>+ provider.random v2.2.1

We get 
`"addons_config.0.kubernetes_dashboard": [REMOVED] The Kubernetes Dashboard addon is removed for clusters on GKE.`

**Comment by autero1** [comment]
Hi, could you provide a bit more details about the issue you're facing?

**Comment by arashbi** [comment]
In the latest version of plugin. When I try to create a cluster, it gives me the mentioned error. The script has a flag to install the dashboard but the dashy is completely gone, so it throws an error

**Comment by craigedmunds** [comment]
![image](https://user-images.githubusercontent.com/1453591/71677198-7a5af080-2d82-11ea-93c2-fcb07395faeb.png)

**Comment by robmorgan** [comment]
Fixed in https://github.com/gruntwork-io/terraform-google-gke/releases/tag/v0.4.0
