### ISSUE TITLE
Following the instructions from your google blog post, and I'm getting errors

### ISSUE THREAD

**Issue by ryanwinchester** [gruntwork-io/terraform-google-gke#72]
https://cloud.google.com/blog/products/devops-sre/deploying-a-production-grade-helm-release-on-gke-with-terraform

I clicked on the first "**open in google cloud shell**" button which clones this repo and has some config scripts loaded.

Following the instructions on the right side, I get to `terraform apply` and, from the error messages, it looks like the string values aren't being interpolated?

![Screen Shot 2019-12-08 at 7 32 17 PM](https://user-images.githubusercontent.com/2897340/70405459-20207700-19f2-11ea-9f66-e54d0f9837ab.png)

This is my first time dabbling in Terraform (and Kubernetes), so I'm completely lost as to what's wrong.

**Comment by autero1** [comment]
Hi, the issue might be that the example is using `terraform 0.11.x`, while the image that's loaded uses latest `terraform:latest` Cloud Shell environment. I'll look into this - sorry for the inconvenience.

**Comment by autero1** [comment]
Fixed in #75
