### ISSUE TITLE
Getting error during private cluster installation

### ISSUE THREAD

**Issue by Babug01** [gruntwork-io/terraform-google-gke#73]
I'm getting below error, when try to create the private cluster in gke.

Made below config to true in main.tf
install_tiller = true

Error: Error running command 'kubergrunt tls gen --ca --namespace kube-system --secret-name kube-system-namespace-tiller-ca-certs --secret-label gruntwork.io/tiller-namespace=kube-system --secret-label gruntwork.io/tiller-credentials=true --secret-label gruntwork.io/tiller-credentials-type=ca --tls-subject-json '{"common_name":"tiller","org":"Gruntwork"}' --tls-private-key-algorithm ECDSA --tls-private-key-ecdsa-curve P256 --kubectl-server-endpoint "$KUBECTL_SERVER_ENDPOINT" --kubectl-certificate-authority "$KUBECTL_CA_DATA" --kubectl-token "$KUBECTL_TOKEN"

kubergrunt tls gen --namespace kube-system --ca-secret-name kube-system-namespace-tiller-ca-certs --ca-namespace kube-system --secret-name tiller-certs --secret-label gruntwork.io/tiller-namespace=kube-system --secret-label gruntwork.io/tiller-credentials=true --secret-label gruntwork.io/tiller-credentials-type=server --tls-subject-json '{"common_name":"tiller","org":"Gruntwork"}' --tls-private-key-algorithm ECDSA --tls-private-key-ecdsa-curve P256 --kubectl-server-endpoint "$KUBECTL_SERVER_ENDPOINT" --kubectl-certificate-authority "$KUBECTL_CA_DATA" --kubectl-token "$KUBECTL_TOKEN"
': exit status 127. Output: /bin/sh: 1: kubergrunt: not found
/bin/sh: 3: kubergrunt: not found

Anyone help me to fix this issue.

**Comment by autero1** [comment]
Seems you don't have `kubergrunt` installed. How are you using the module? Please note that the root of this repo contains an example, not the GKE module itself - the example is documented [here](https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-private-tiller). The `Tiler` example specifies a number of tools  you have to install before running it.

See https://github.com/gruntwork-io/terraform-google-gke/tree/master/modules/gke-cluster#how-do-you-use-this-module for complete instructions on how to use the GKE module.

**Comment by Babug01** [comment]
I think the same. Because I didn't use circleci codes, which is available in this git repo. I copied only the terraform codes and modules.

Do i need to install kubergrunt in local system?

**Comment by autero1** [comment]
Yes, follow the instructions here: https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-private-tiller

**Comment by Babug01** [comment]
Thanks @autero1. The above mentioned error was fixed and cluster is installed successfully.
But, when i tried to see the available pods in my cluster, I'm getting below message
(zoover-262116)$ kubectl get services
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Do you have any idea on this message? Where I need to specify my ports

**Comment by autero1** [comment]
You have to generate a `kubeconfig` entry in your environment. See https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry for instructions.

If you need to acces `helm`, you will need to configure `helm` with `kubergrunt`: https://github.com/gruntwork-io/kubergrunt#helm-configure

**Comment by Babug01** [comment]
Thanks @autero1. Issue fixed
