### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by inductor** [gruntwork-io/terraform-google-gke#76]
looking at https://github.com/gruntwork-io/terraform-google-gke/tree/v0.1.1/modules/gke-cluster, it seems it's not been changed for a half year.

**Comment by robmorgan** [comment]
Hi @inductor yes, it is. I noticed you're referencing quite an older version, you can see our latest releases here: https://github.com/gruntwork-io/terraform-google-gke/releases
