### ISSUE TITLE
Variable enable_legacy_abac isn't work

### ISSUE THREAD

**Issue by vscoder** [gruntwork-io/terraform-google-gke#79]
# How to reproduce

In module `gke-cluster` is defined variable
https://github.com/gruntwork-io/terraform-google-gke/blob/8fcecd85a852c51f7e3dfa8f43de12c530a66cf3/modules/gke-cluster/variables.tf#L158-L162

I set value for this variable to `true`
```
module "gke_cluster" {
  ...
  enable_legacy_abac = "true"
}
```

# Expected behaviour

When i do `terraform apply`, i expect to see:
```
  # module.gke_cluster.google_container_cluster.cluster will be created
  + resource "google_container_cluster" "cluster" {
      ...
      + enable_legacy_abac          = true
```

# Real behavior

When i do `terraform apply`, i see:
```
  # module.gke_cluster.google_container_cluster.cluster will be created
  + resource "google_container_cluster" "cluster" {
      ...
      + enable_legacy_abac          = false
```

# How to fix

In file `modules/gke-cluster/main.tf` block `resource "google_container_cluster" "cluster" {...}` add
```
resource "google_container_cluster" "cluster" {
  enable_legacy_abac = var.enable_legacy_abac
  ...
}
```

**Comment by robmorgan** [comment]
Fixed in https://github.com/gruntwork-io/terraform-google-gke/pull/80
