### ISSUE TITLE
Already existing node pool marked as to be created in plan

### ISSUE THREAD

**Issue by nickdk** [gruntwork-io/terraform-google-gke#87]
### Terraform Version

0.12.24

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Relevant config:

```tfresource "google_container_node_pool" "node_pool" {
  provider = google-beta

  name     = "private-pool"
  project  = var.project
  location = var.location
  cluster  = module.gke_cluster.name

  initial_node_count = var.cluster_nodepool_min_nodes

  autoscaling {
    min_node_count = var.cluster_nodepool_min_nodes
    max_node_count = var.cluster_nodepool_max_nodes
  }

  management {
    auto_repair  = "true"
    auto_upgrade = "true"
  }

  node_config {
    image_type   = "COS"
    machine_type = var.cluster_nodepool_machine_type

    labels = {
      private-pools-example = "true"
    }

    # Add a private tag to the instances. See the network access tier table for full details:
    # https://github.com/gruntwork-io/terraform-google-network/tree/master/modules/vpc-network#access-tier
    tags = [
      module.vpc_network.private,
      "private-pool-example",
    ]

    disk_size_gb = "30"
    disk_type    = "pd-standard"
    preemptible  = false

    service_account = module.gke_service_account.email

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  lifecycle {
    ignore_changes = [initial_node_count]
  }

  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }
}
```

### Debug Output

```# module.gke-cluster.google_container_node_pool.node_pool will be created
  + resource "google_container_node_pool" "node_pool" {
      + cluster             = "web-cluster"
      + id                  = (known after apply)
      + initial_node_count  = 2
      + instance_group_urls = (known after apply)
      + location            = "europe-west1"
      + max_pods_per_node   = (known after apply)
      + name                = "private-pool"
      + name_prefix         = (known after apply)
      + node_count          = (known after apply)
      + node_locations      = (known after apply)
      + project             = "redacted-web"
      + region              = (known after apply)
      + version             = (known after apply)
      + zone                = (known after apply)
      + autoscaling {
          + max_node_count = 2
          + min_node_count = 2
        }
      + management {
          + auto_repair  = true
          + auto_upgrade = true
        }
      + node_config {
          + disk_size_gb      = 30
          + disk_type         = "pd-standard"
          + guest_accelerator = (known after apply)
          + image_type        = "COS"
          + labels            = {
              + "private-pools-example" = "true"
            }
          + local_ssd_count   = (known after apply)
          + machine_type      = "n1-highmem-16"
          + metadata          = (known after apply)
          + oauth_scopes      = [
              + "https://www.googleapis.com/auth/cloud-platform",
            ]
          + preemptible       = false
          + service_account   = "web-gke-sa@redacted.iam.gserviceaccount.com"
          + tags              = [
              + "private",
              + "private-pool-example",
            ]
          + shielded_instance_config {
              + enable_integrity_monitoring = (known after apply)
              + enable_secure_boot          = (known after apply)
            }
        }
      + timeouts {
          + create = "30m"
          + delete = "30m"
          + update = "30m"
        }
    }
```

### Expected Behavior

No changes to the node pool, it already exists and no config has been changed since last apply.

### Actual Behavior

If applied following error is thrown to indicate the node pool to be created already exists:
```Error: error creating NodePool: googleapi: Error 409: Already exists: projects/outspot-web/locations/europe-west1/clusters/web-cluster/nodePools/private-pool., alreadyExists
  on ../modules/gke-cluster/main.tf line 49, in resource "google_container_node_pool" "node_pool":
  49: resource "google_container_node_pool" "node_pool" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Could it have anything to do with the Kubernetes version of the nodes? We currently have a kubernetes node upgrade available from 1.15.9-gke.24 (current) to 1.15.9-gke.26. Wondering if this could have an impact in terraform seeing these as different node pools?

**Comment by nickdk** [comment]
This issue can be closed, it turned out since the node pool remained in a RUNNING_WITH_ERROR state after an IP problem that was resolved it didn't properly end up in the state file.

This behaviour has apparently been tackled in later versions of the Google provider, see:
https://github.com/terraform-providers/terraform-provider-google/issues/3304
https://github.com/terraform-providers/terraform-provider-google/pull/5662

I think it does raise a question to the gruntwork team, are there any plans to upgrade to newer versions of the Google provider?

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
