### ISSUE TITLE
When enable_network_policy is set to false cluster fails to deploy

### ISSUE THREAD

**Issue by ulm0** [gruntwork-io/terraform-google-gke#95]
Setting `enable_network_policy` to `false` causes cluster creation to fail
https://github.com/gruntwork-io/terraform-google-gke/blob/fc50e72bd10310d97108d18f2a70a9e2d47c6b50/modules/gke-cluster/main.tf#L93

Due to this hard-coded value
https://github.com/gruntwork-io/terraform-google-gke/blob/fc50e72bd10310d97108d18f2a70a9e2d47c6b50/modules/gke-cluster/main.tf#L96

Using the following works

```hcl
provider = var.enable_network_policy ? "CALICO" : "PROVIDER_UNSPECIFIED"
```

**Comment by robmorgan** [comment]
Hi @ulm0, would you be willing to submit a PR for this?

**Comment by ulm0** [comment]
@robmorgan sure, just did #99

**Comment by robmorgan** [comment]
@ulm0 thanks!
