### ISSUE TITLE
Terraform code for GCP private cluster not working

### ISSUE THREAD

**Issue by rg2609** [gruntwork-io/terraform-google-gke#96]
I have the terraform code for GCP private cluster and it was working one month back, but today I am trying it and it's giving error now.

```
Error: googleapi: Error 400: Alias IP addresses are required for private cluster, please make sure you enable alias IPs when creating a cluster., badRequest

  on modules/gke-cluster/main.tf line 20, in resource "google_container_cluster" "cluster":
  20: resource "google_container_cluster" "cluster" {
```
Am I missing something? Help will be appreciated

**Comment by rg2609** [comment]
Is anyone know the solution, that will be appreciated.

**Comment by robmorgan** [comment]
hi @rg2609 are you still having this issue?

**Comment by Etiene** [comment]
### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
